### ISSUE TITLE
Add a '.throttle' method

### ISSUE THREAD

**Issue by rjnienaber** [blend/promise-utils#40]
I seem to have this need every so often and keep finding myself redefining the same function over and over again in multiple projects. The point of the function is to take an array of functions that produce a promise but will only start 10 (configurable) promises at a time. 

A real-world example I've had recently was to download all the URLs listed in a file, with no more than 10 requests at a time:

```typescript
  const fileData = await fs.promises.readFile('urls.txt', 'utf-8') as string;
  const fileLines = fileData.split('\n');

  const promiseFuncs = fileLines.map((l) => () => downloadUrl(l));
  await promiseThrottle(promiseFuncs, 10);
```
The code for `promiseThrottle` looks like this:

```typescript
export async function promiseThrottle(promiseFuncs: any[], max = 10) {
  const executingPromises = [];
  const results = [];
  while (executingPromises.length !== 0 || promiseFuncs.length !== 0) {
    while (executingPromises.length < max && promiseFuncs.length !== 0) {
      const promise = promiseFuncs.shift()().then((result: any) => {
        promise.done = true;
        return result;
      });
      executingPromises.push(promise);
    }

    results.push(await Promise.race(executingPromises));
    executingPromises.splice(executingPromises.findIndex((p) => p.done), 1);
  }

  return results;
}
```
In the above example, `downloadUrl` saves to disk as a side-effect (because there were 1000s of web pages) but it could also return its results when all promises have been run.

Do you think there's a place for something like this functionality in `promiseUtils` ?

**Comment by ftrimble** [comment]
I think this is already implemented in `promiseUtils.mapLimit` - what would you want from that function that isn't already built in?

**Comment by ftrimble** [comment]
Also, fwiw - I'm not sure that as written your code actually implements the throttling correctly. Since you've already created the promises, they are going to get executed whether you are awaiting them or not. You need to only invoke the function that generates the promise when there is sufficient remaining concurrency to deal with it.

**Comment by rjnienaber** [comment]
Sorry, you're absolutely right not sure how I missed it when looking through the docs.  `promiseUtils.mapLimit`  is what I'm looking for!

The `promiseThrottle` function will work because of `promiseFuncs.shift()()` which will invoke the function that returns the promise which will then start executing.

**Comment by ftrimble** [comment]
ah ya i didn't notice that the original map returned a lambda, not just invoked one.
